---
output: html_document
params:
  set_title: NA
  set_date: NA
  set_author: NA
  table: NA
  move_plot: NA
  network_plot: NA
  epiplot_version: NA
  comments: NA
  date_min: NA
  date_max: NA
  genotype: NA
  species: NA
title: "`r params$set_title`"
date: "`r params$set_date`"
author: "`r params$set_author`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```
Ce rapport a été généré avec les données suivantes:  

* Nombre de patients: `r nrow(params$table)`
* Dates: `r params$date_min` et le `r params$date_max`
* Organisme: `r params$species`
* Génotype: `r params$genotype`
  
EpiPlot `r params$epiplot_version`

# Commentaires
`r params$comments`  

# Données
```{r echo=F}
sum_table <- params$table
colnames(sum_table) <- gsub("_", " ", colnames(sum_table))
knitr::kable(sum_table, 
             align = "c",
             digits = 1,
             caption = "Résumé des séjours de chaque patient à l'hôpital.")
```

```{r echo=F, out.width = "100%", fig.cap="Mouvements des patients à l'hôpital. Les mouvements sont représentés par des barres indiquant la durée de séjour de chaque patient dans une unité. Les différentes unités sont distinguées par un code couleur. Pour chaque patient, les prélèvements positifs et négatifs sont marqués respectivement par un losange rouge et un rond vert."}
params$move_plot
```

```{r echo=F, out.width = "100%", fig.cap="Réseau montrant les liens épidémiologiques potentiels entre les patients. Chaque patient est représenté par un cercle, et les liens entre les cercles indiquent le nombre de jours passés par ces patients dans la même unité au même moment."}
params$network_plot
```
  
Epiplot version `r params$epiplot_version`